[package]
name = "e_shop_project"
version = "0.1.0"
edition = "2021"

[dependencies]
anymap.version = "1.0.0-beta.2"
serde = {version = "1.0.215", features = ["derive"] }
diesel = { version = "2.2.0", features = ["postgres"] }
dotenvy = "0.15"
# logging
simple_logger = "5.0.0"
log = "0.4"