# 20160107082941_create_posts/metadata.toml

# specifices if a migration is executed inside a
# transaction or not. This configuration is optional
# by default all migrations are run in transactions.
#
# For certain types of migrations, like creating an
# index onto a existing column, it is required
# to set this to false
run_in_transaction = false